[project]
name = "deploy-or-not"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.14"
dependencies = [
    "django-cors-headers>=4.9.0",
    "django-modern-rest[msgspec,openapi,pydantic]>=0.14.0",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
dev = [
    "django-stubs>=6.1.0",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 100
target-version = "py313"
exclude = ["migrations"]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "UP",
    "B",
    "C4",
    "SIM",
    "DJ",
    "ASYNC",
    "RUF",
]
ignore = [
    "DJ001",
]

[tool.ruff.lint.isort]
known-first-party = ["config", "api"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"


[tool.mypy]
python_version = "3.13"
plugins = ["mypy_django_plugin.main"]
strict = true
warn_unused_ignores = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

[tool.django-stubs]
django_settings_module = "config.settings"
